language: php
php:
  - 7
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm
script:
  - composer install
  - bin/phpunit --coverage-clover=coverage.clover
sudo: false

after_success:
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
